build:
    environment:
        php:
            version: 7.0.8
        postgresql: false
        redis: false
        mysql: 5.5
    dependencies:
        before: 
            - mysql -h 127.0.0.1 -u root -e 'create database cat'
            - mysql -h 127.0.0.1 -u root cat < schema/schema.sql
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
filter:
    excluded_paths: [web/external/*, core/phpqrcode.php, config/config-template.php, devices/devices-template.php]

