build:
    environment:
        php:
            version: 7.0.8
	postgresql: false
	redis:	false

filter:
    excluded_paths: [web/external/*, core/phpqrcode.php, config/config-template.php, devices/devices-template.php]

